In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv(r"C:/Users/DELL/Desktop/data/ML/fitness_class_2212.csv")

In [3]:
df.head()

booking_id  months_as_member  weight days_before day_of_week time  \
0           1                17   79.56           8         Wed   PM   
1           2                10   79.01           2         Mon   AM   
2           3                16   74.53          14         Sun   AM   
3           4                 5   86.12          10         Fri   AM   
4           5                15   69.29           8         Thu   AM   

   category  attended  
0  Strength         0  
1      HIIT         0  
2  Strength         0  
3   Cycling         0  
4      HIIT         0

In [4]:
df.shape

(1500, 8)

In [5]:
df.isnull().sum()

booking_id           0
months_as_member     0
weight              20
days_before          0
day_of_week          0
time                 0
category             0
attended             0
dtype: int64

In [6]:
df['weight'].fillna(df['weight'].mean , inplace = True)

In [7]:
df.isnull().sum()

booking_id          0
months_as_member    0
weight              0
days_before         0
day_of_week         0
time                0
category            0
attended            0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   booking_id        1500 non-null   int64 
 1   months_as_member  1500 non-null   int64 
 2   weight            1500 non-null   object
 3   days_before       1500 non-null   object
 4   day_of_week       1500 non-null   object
 5   time              1500 non-null   object
 6   category          1500 non-null   object
 7   attended          1500 non-null   int64 
dtypes: int64(3), object(5)
memory usage: 93.9+ KB


In [9]:
df['weight']= pd.to_numeric(df['weight'],errors='coerce')

In [10]:
df['days_before']= pd.to_numeric(df['days_before'],errors='coerce')

In [11]:
df['day_of_week'].value_counts()

Fri          279
Thu          241
Mon          218
Sun          213
Sat          202
Tue          195
Wed           81
Wednesday     35
Fri.          26
Monday        10
Name: day_of_week, dtype: int64

In [12]:
df['day_of_week']= df['day_of_week'].str.replace("Monday", "Mon")
df['day_of_week']= df['day_of_week'].str.replace("Wednesday", "Wed")
df['day_of_week']= df['day_of_week'].str.replace("Fri.", "Fri")

In [13]:
df['day_of_week'].value_counts()

Fri    305
Thu    241
Mon    228
Sun    213
Sat    202
Tue    195
Wed    116
Name: day_of_week, dtype: int64

In [14]:
df['time'].value_counts()

AM    1141
PM     359
Name: time, dtype: int64

In [15]:
df['category'].value_counts()

HIIT        667
Cycling     376
Strength    233
Yoga        135
Aqua         76
-            13
Name: category, dtype: int64

In [16]:
status = pd.get_dummies(df[['day_of_week','time','category']], drop_first= True)
df = pd.concat([df,status],axis =1)

In [17]:
df.drop(['day_of_week','time','category'], axis =1 , inplace = True)

In [18]:
df.head()

booking_id  months_as_member  weight  days_before  attended  \
0           1                17   79.56          8.0         0   
1           2                10   79.01          2.0         0   
2           3                16   74.53         14.0         0   
3           4                 5   86.12         10.0         0   
4           5                15   69.29          8.0         0   

   day_of_week_Mon  day_of_week_Sat  day_of_week_Sun  day_of_week_Thu  \
0                0                0                0                0   
1                1                0                0                0   
2                0                0                1                0   
3                0                0                0                0   
4                0                0                0                1   

   day_of_week_Tue  day_of_week_Wed  time_PM  category_Aqua  category_Cycling  \
0                0                1        1              0                 0   
1                0                0        0              0                 0   
2                0                0        0              0                 0   
3                0                0        0              0                 1   
4                0                0        0              0                 0   

   category_HIIT  category_Strength  category_Yoga  
0              0                  1              0  
1              1                  0              0  
2              0                  1              0  
3              0                  0              0  
4              1                  0              0

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   booking_id         1500 non-null   int64  
 1   months_as_member   1500 non-null   int64  
 2   weight             1480 non-null   float64
 3   days_before        1475 non-null   float64
 4   attended           1500 non-null   int64  
 5   day_of_week_Mon    1500 non-null   uint8  
 6   day_of_week_Sat    1500 non-null   uint8  
 7   day_of_week_Sun    1500 non-null   uint8  
 8   day_of_week_Thu    1500 non-null   uint8  
 9   day_of_week_Tue    1500 non-null   uint8  
 10  day_of_week_Wed    1500 non-null   uint8  
 11  time_PM            1500 non-null   uint8  
 12  category_Aqua      1500 non-null   uint8  
 13  category_Cycling   1500 non-null   uint8  
 14  category_HIIT      1500 non-null   uint8  
 15  category_Strength  1500 non-null   uint8  
 16  category_Yoga      1500 

In [20]:
df.isnull().sum()

booking_id            0
months_as_member      0
weight               20
days_before          25
attended              0
day_of_week_Mon       0
day_of_week_Sat       0
day_of_week_Sun       0
day_of_week_Thu       0
day_of_week_Tue       0
day_of_week_Wed       0
time_PM               0
category_Aqua         0
category_Cycling      0
category_HIIT         0
category_Strength     0
category_Yoga         0
dtype: int64

In [21]:
df= df.dropna()

In [22]:
df.isnull().sum()

booking_id           0
months_as_member     0
weight               0
days_before          0
attended             0
day_of_week_Mon      0
day_of_week_Sat      0
day_of_week_Sun      0
day_of_week_Thu      0
day_of_week_Tue      0
day_of_week_Wed      0
time_PM              0
category_Aqua        0
category_Cycling     0
category_HIIT        0
category_Strength    0
category_Yoga        0
dtype: int64

In [23]:
df.shape

(1455, 17)

In [24]:
X = df.drop(['attended'],axis=1)
y= df['attended']

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [28]:
X_train.shape

(1018, 16)

In [29]:
X_test.shape

(437, 16)

In [31]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()

In [32]:
X_train = minmax.fit_transform(X_train)

In [33]:
X_test = minmax.fit_transform(X_test)

In [34]:
X_train

array([[0.31887925, 0.1292517 , 0.3720376 , ..., 1.        , 0.        ,
        0.        ],
       [0.32421614, 0.31972789, 0.32132927, ..., 1.        , 0.        ,
        0.        ],
       [0.91194129, 0.04761905, 0.28942142, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.88725817, 0.05442177, 0.21342513, ..., 0.        , 0.        ,
        0.        ],
       [0.59106071, 0.        , 0.72381835, ..., 0.        , 0.        ,
        1.        ],
       [0.77318212, 0.12244898, 0.40182709, ..., 1.        , 0.        ,
        0.        ]])

In [35]:
X_test

array([[0.33781965, 0.125     , 0.14655547, ..., 1.        , 0.        ,
        0.        ],
       [0.86473755, 0.125     , 0.28225176, ..., 0.        , 0.        ,
        0.        ],
       [0.27792732, 0.38461538, 0.15480844, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.49461642, 0.23076923, 0.16731822, ..., 1.        , 0.        ,
        0.        ],
       [0.36608345, 0.15384615, 0.22543654, ..., 1.        , 0.        ,
        0.        ],
       [0.08546433, 0.11538462, 0.35235861, ..., 0.        , 0.        ,
        0.        ]])

In [36]:
y_train.shape

(1018,)

In [37]:
y_test.shape

(437,)

In [38]:
y_train = np.array(y_train)
y_train  = y_train.reshape(1018,-1)

In [39]:
y_train.shape

(1018, 1)

In [40]:
y_test = np.array(y_test)
y_test  = y_test.reshape(437,-1)

In [41]:
y_test.shape

(437, 1)

In [44]:
X_test.shape

(437, 16)

In [45]:
X_train.shape

(1018, 16)

# Model1

In [46]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [47]:
logreg.fit(X_train,y_train)

LogisticRegression()

In [48]:
y_pred = logreg.predict(X_test)

In [49]:
from sklearn import metrics

In [50]:
confusion = metrics.confusion_matrix(y_test,y_pred)
print(confusion)

[[265  30]
 [ 75  67]]


In [56]:
print(metrics.accuracy_score(y_test,y_pred))

0.7597254004576659


# Model 2

In [51]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [52]:
svm_classifier = SVC(kernel = 'linear')

In [53]:
svm_classifier.fit(X_train,y_train)

SVC(kernel='linear')

In [54]:
from sklearn import metrics

In [55]:
confusion = metrics.confusion_matrix(y_test,y_pred)
print(confusion)

[[265  30]
 [ 75  67]]


In [57]:
print(metrics.accuracy_score(y_test,y_pred))

0.7597254004576659
